[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc_version = "0.8.17"
remappings = ['@openzeppelin/contracts=lib/openzeppelin-contracts/contracts', '@zondax/filecoin-solidity=lib/filecoin-solidity', '@zondax/solidity-bignumber=lib/solidity-bignumber','foundry-devops/=lib/foundry-devops/']
optimizer = true
ffi = true
[etherscan]
mainnet = { key = "${ETHERSCAN_API_KEY}" }
sepolia = {key = "${ETHERSCAN_API_KEY}"}

[rpc_endpoints]
sepolia = "${SEPOLIA_RPC_URL}"

# See more config options https://github.com/foundry-rs/foundry/tree/master/config